import { Product } from './product.model';
import { Order } from './order.model';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Classic Oxford Dress Shirt',
    description: 'Premium cotton Oxford dress shirt with a timeless button-down collar. Perfect for business and formal occasions. Crafted from 100% Egyptian cotton for supreme comfort.',
    price: 2499,
    originalPrice: 3499,
    category: 'clothing',
    brand: 'Heritage & Co.',
    rating: 4.7,
    reviewCount: 284,
    stock: 45,
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600'],
    tags: ['formal', 'cotton', 'shirt'],
    isFeatured: true,
    isNew: false
  },
  {
    id: 2,
    name: 'Leather Briefcase Portfolio',
    description: 'Handcrafted full-grain leather briefcase with multiple compartments. Holds up to 15" laptop. Antique brass hardware for a distinguished look.',
    price: 8999,
    originalPrice: 12000,
    category: 'accessories',
    brand: 'Artisan Craft',
    rating: 4.9,
    reviewCount: 156,
    stock: 12,
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600'],
    tags: ['leather', 'bag', 'office'],
    isFeatured: true,
    isNew: false
  },
  {
    id: 3,
    name: 'Swiss Automatic Wristwatch',
    description: 'Elegant Swiss-made automatic movement watch with sapphire crystal glass. Water resistant to 50 meters. Stainless steel case with genuine leather strap.',
    price: 24999,
    originalPrice: 32000,
    category: 'watches',
    brand: 'Geneva Timepiece',
    rating: 4.8,
    reviewCount: 98,
    stock: 8,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600'],
    tags: ['watch', 'luxury', 'swiss'],
    isFeatured: true,
    isNew: true
  },
  {
    id: 4,
    name: 'Merino Wool Blazer',
    description: 'Tailored merino wool blazer with a modern slim fit. Features two-button closure, notch lapels, and a fully lined interior. Available in charcoal and navy.',
    price: 6499,
    originalPrice: 8999,
    category: 'clothing',
    brand: 'Heritage & Co.',
    rating: 4.5,
    reviewCount: 203,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4b5c2a?w=600'],
    tags: ['blazer', 'wool', 'formal'],
    isFeatured: false,
    isNew: false
  },
  {
    id: 5,
    name: 'Noise-Cancelling Headphones',
    description: 'Premium over-ear headphones with active noise cancellation and 30-hour battery life. Hi-Res Audio certified with plush memory foam ear cushions.',
    price: 18999,
    originalPrice: 24999,
    category: 'electronics',
    brand: 'SoundCraft Pro',
    rating: 4.6,
    reviewCount: 512,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600'],
    tags: ['audio', 'wireless', 'noise-cancelling'],
    isFeatured: true,
    isNew: false
  },
  {
    id: 6,
    name: 'Genuine Leather Oxford Shoes',
    description: 'Classic cap-toe Oxford shoes in full-grain calf leather. Hand-stitched welted construction for durability and easy resoling. Leather-lined for breathability.',
    price: 7999,
    originalPrice: 10500,
    category: 'footwear',
    brand: 'Cobbler\'s Guild',
    rating: 4.7,
    reviewCount: 178,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600'],
    tags: ['shoes', 'leather', 'formal'],
    isFeatured: false,
    isNew: true
  },
  {
    id: 7,
    name: 'Cashmere Turtleneck Sweater',
    description: 'Luxurious 100% Grade A cashmere turtleneck sweater. Soft, warm and lightweight. Features ribbed cuffs, hem and collar for a refined finish.',
    price: 5499,
    originalPrice: 7500,
    category: 'clothing',
    brand: 'Cashmere House',
    rating: 4.8,
    reviewCount: 142,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600'],
    tags: ['cashmere', 'sweater', 'winter'],
    isFeatured: false,
    isNew: false
  },
  {
    id: 8,
    name: 'Fountain Pen Set',
    description: 'Premium stainless steel fountain pen with 24k gold-plated nib. Includes ink converter and six ink cartridges in a luxury gift box. Perfect for collectors.',
    price: 3299,
    originalPrice: 4500,
    category: 'stationery',
    brand: 'Scrivenwright',
    rating: 4.9,
    reviewCount: 89,
    stock: 18,
    images: ['https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600'],
    tags: ['pen', 'writing', 'gift'],
    isFeatured: false,
    isNew: true
  },
  {
    id: 9,
    name: 'Slim Fit Chino Trousers',
    description: 'Versatile stretch-cotton chino trousers with a modern slim fit. Features a flat front, side pockets, and a tailored hemline. Machine washable.',
    price: 2299,
    originalPrice: 3200,
    category: 'clothing',
    brand: 'Heritage & Co.',
    rating: 4.4,
    reviewCount: 321,
    stock: 60,
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600'],
    tags: ['trousers', 'chino', 'casual'],
    isFeatured: false,
    isNew: false
  },
  {
    id: 10,
    name: 'Wireless Charging Pad',
    description: 'Fast 15W Qi wireless charging pad compatible with all Qi-enabled devices. Ultra-slim design with LED indicator. Includes braided USB-C cable.',
    price: 1799,
    originalPrice: 2499,
    category: 'electronics',
    brand: 'ChargeTech',
    rating: 4.3,
    reviewCount: 445,
    stock: 80,
    images: ['https://images.unsplash.com/photo-1585338447937-7082f8fc763d?w=600'],
    tags: ['charging', 'wireless', 'tech'],
    isFeatured: false,
    isNew: false
  },
  {
    id: 11,
    name: 'Italian Silk Tie',
    description: 'Handmade Italian silk tie with a classic diagonal stripe pattern. Seven-fold construction for superior drape. Comes in a premium gift box.',
    price: 1999,
    originalPrice: 2800,
    category: 'accessories',
    brand: 'Milano Seta',
    rating: 4.6,
    reviewCount: 167,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600'],
    tags: ['tie', 'silk', 'formal'],
    isFeatured: false,
    isNew: false
  },
  {
    id: 12,
    name: 'Scented Candle Collection',
    description: 'Set of three hand-poured soy wax candles in classic amber glass jars. Fragrances: Sandalwood & Cedar, Vanilla & Jasmine, Sea Breeze & Citrus. 50-hour burn time each.',
    price: 2799,
    originalPrice: 3600,
    category: 'home',
    brand: 'Lumière Home',
    rating: 4.7,
    reviewCount: 234,
    stock: 22,
    images: ['https://images.unsplash.com/photo-1602874801006-36cff680c8ee?w=600'],
    tags: ['candle', 'home', 'gift'],
    isFeatured: false,
    isNew: true
  }
];

export const MOCK_CATEGORIES = [
  { id: 'all', name: 'All Products', icon: '🛍️' },
  { id: 'clothing', name: 'Clothing', icon: '👔' },
  { id: 'accessories', name: 'Accessories', icon: '👜' },
  { id: 'watches', name: 'Watches', icon: '⌚' },
  { id: 'electronics', name: 'Electronics', icon: '🎧' },
  { id: 'footwear', name: 'Footwear', icon: '👞' },
  { id: 'stationery', name: 'Stationery', icon: '🖊️' },
  { id: 'home', name: 'Home & Living', icon: '🕯️' },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-2026-00142',
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 2 },
      { product: MOCK_PRODUCTS[4], quantity: 1 }
    ],
    status: 'shipped',
    shippingAddress: {
      fullName: 'Jyothisha R',
      phone: '+91 98765 43210',
      addressLine1: '42, Residency Road',
      addressLine2: 'Near Town Hall',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560025'
    },
    subtotal: 23997,
    tax: 4319,
    shipping: 0,
    total: 28316,
    placedAt: new Date('2026-04-18T10:30:00'),
    estimatedDelivery: new Date('2026-04-26T18:00:00'),
    trackingEvents: [
      { status: 'pending', label: 'Order Placed', description: 'Your order has been received.', timestamp: new Date('2026-04-18T10:30:00'), completed: true, icon: '📋' },
      { status: 'confirmed', label: 'Order Confirmed', description: 'Payment verified and order confirmed.', timestamp: new Date('2026-04-18T11:15:00'), completed: true, icon: '✅' },
      { status: 'processing', label: 'Processing', description: 'Your items are being packed.', timestamp: new Date('2026-04-19T09:00:00'), completed: true, icon: '📦' },
      { status: 'shipped', label: 'Shipped', description: 'Package handed over to courier. Tracking: DL9823741.', timestamp: new Date('2026-04-20T14:30:00'), completed: true, icon: '🚚' },
      { status: 'out_for_delivery', label: 'Out for Delivery', description: 'Your package is out for delivery.', timestamp: null, completed: false, icon: '🛵' },
      { status: 'delivered', label: 'Delivered', description: 'Package delivered successfully.', timestamp: null, completed: false, icon: '🎉' },
    ],
    paymentMethod: 'Credit Card ending 4242'
  }
];
